scalar Date

type User {
  id: String
  name: String
  email: String
  admin: Boolean
  created_at: Date
  updated_at: Date
}

type Query {
  getAllUser: [User]
}

input UserInput {
  name: String
  userName: String
  email: String
}

type Mutation {
  createUser(input: UserInput): User
}